services:
  kb-ingestor:
    build: .
    container_name: kb-ingestor
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8888 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s